HumanResourceSuite.WebFront/Models/ErrorViewModel.cs
using System;

namespace HumarResourceSuite.WebFront.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

HumanResourceSuite.WebFront/Models/LeadsModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HumanResourceSuite.WebFront.Models
{
    public class LeadsModel
    {
		public int Mode { get; set; }
		public int Id { get; set; }
		public string First_name { get; set; }
		public string Last_name { get; set; }
		public string Mobile_no { get; set; }
		public string Email_address { get; set; }
		public string Company { get; set; }
		public int Industry_type { get; set; }
		public string Created_by { get; set; }
		public string Created_date { get; set; }
		public string Modified_by { get; set; }
		public string Modified_date { get; set; }
	}
}

HumanResourceSuite.WebFront/Controllers/AccountController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using HumarResourceSuite.WebFront.Models;
using HumanResourceSuite.WebFront.Framework;
using HumanResourceSuite.WebFront.ServiceClients;
using HumanResourceSuite.DataObjects;


namespace HumanResourceSuite.WebFront.Controllers
{
    public class AccountController : BaseController
    {
        private readonly ILogger<AccountController> _logger;
        private readonly MasterServiceClient _masterServiceClient;
        private readonly LeadServiceClient _leadServiceClient;
        private readonly CompanyServiceClient _companyServiceClient;
        public AccountController(ILogger<AccountController> logger)
        {
            _logger = logger;
            _masterServiceClient = new MasterServiceClient();
            _leadServiceClient = new LeadServiceClient();
        }
        
        public IActionResult Login()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Login([FromBody] LoginDTO loginDTO)
        {
            return RedirectToAction("Index", "Home");
        }

        public IActionResult ForgetPassword()
        {
            return View();
        }
    }
}

HumanResourceSuite.WebFront/Controllers/CandidateController.cs
using HumanResourceSuite.WebFront.Framework;
using HumanResourceSuite.WebFront.ServiceClients;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HumanResourceSuite.WebFront.Controllers
{
    public class CandidateController : BaseController
    {
        private readonly ILogger<CandidateController> _logger;
        private readonly MasterServiceClient _masterServiceClient;
        private readonly LeadServiceClient _leadServiceClient;
        private readonly EmployeeServiceClient _employeeServiceClient;
        public CandidateController(ILogger<CandidateController> logger)
        {
            _logger = logger;
            _masterServiceClient = new MasterServiceClient();
            _leadServiceClient = new LeadServiceClient();
        }

        public async Task<IActionResult> CandidateIndex()
        {
            //var data = await _employeeServiceClient.GetAll();
            return View();
        }
    }
}

HumanResourceSuite.WebFront/Controllers/EmployeeController.cs
using HumanResourceSuite.WebFront.Framework;
using HumanResourceSuite.WebFront.ServiceClients;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HumanResourceSuite.WebFront.Controllers
{
    public class EmployeeController : BaseController
    {
        private readonly ILogger<EmployeeController> _logger;
        private readonly MasterServiceClient _masterServiceClient;
        private readonly LeadServiceClient _leadServiceClient;
        private readonly EmployeeServiceClient _employeeServiceClient;
        public EmployeeController(ILogger<EmployeeController> logger)
        {
            _logger = logger;
            _masterServiceClient = new MasterServiceClient();
            _leadServiceClient = new LeadServiceClient();
        }

        public IActionResult Index()
        {
            return View("Index");
        }
        public IActionResult ProfileDetails()
        {
            return View("_Profile");
        }
       

        public IActionResult SelfDetails()
        {
            return View("_Self");
        }
        public IActionResult AddressDetails()
        {
            return View("_Address");
        }
        public IActionResult BankDetails()
        {
            return View("_Bank");
        }
        public IActionResult InvestmentDetails()
        {
            return View("_Investment");
        }
        public IActionResult LeaveAndAttendanceDetails()
        {
            return View("_LeaveAndAttendance");
        }
        public IActionResult QualificationDetails()
        {
            return View("_Qualification");
        }
        public IActionResult SalaryDetails()
        {
            return View("_Salary");
        }
        public IActionResult TenureDetails()
        {
            return View("_Tenure");
        }
        public IActionResult EmploymentDetails()
        {
            return View("_Employment");
        }

    }
}

HumanResourceSuite.WebFront/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using HumarResourceSuite.WebFront.Models;
using HumanResourceSuite.WebFront.Framework;
using HumanResourceSuite.WebFront.ServiceClients;
using HumanResourceSuite.DataObjects;
using HumanResourceSuite.WebFront.Models;
using Microsoft.AspNetCore.Authorization;
using javax.jws;

namespace HumarResourceSuite.WebFront.Controllers
{
    public class HomeController : BaseController
    {
        private readonly ILogger<HomeController> _logger;
        private readonly MasterServiceClient _masterServiceClient;
        private readonly LeadServiceClient _leadServiceClient;
        private readonly CompanyServiceClient _companyServiceClient;
        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
            _masterServiceClient = new MasterServiceClient();
            _leadServiceClient = new LeadServiceClient();
        }
        
        public async Task<IActionResult> Index()
        {
           //var data = await _masterServiceClient.GetAll();
            return View();
        }

        public async Task<IActionResult> LeadIndex()
        {
            return View();
        }

        //public PartialViewResult EmployeeSelfPartial()
        //{
        //    return PartialView("_EmployeeSelf");
        //}



        //[WebMethod]
        //public static string LeadCreateAndUpdate([FromBody] LeadsModel leadsDTO)
        //{
        //    return "success";   //Json(data.ToString());
        //}

        [AcceptVerbs("Post", "GET")]
        public async Task<IActionResult> LeadCreateAndUpdate(LeadsModel leadsDTO)
        {
            //var data = await _leadServiceClient.Insert(leadsDTO);
            return PartialView("_IndexPartial");   //Json(data.ToString());
        }

       // [HttpPost]
        //public PartialViewResult LeadCreateAndUpdate1([FromBody] int id)
        //{
        //   // var data = await _leadServiceClient.Insert(leadsModel);
        //    return PartialView("_IndexPartial");   //Json(data.ToString());
        //}
       
        public async Task<IActionResult> CompanyIndex()
        {
            return View();
        }

        [AllowAnonymous]
        [HttpPost]
        public async Task<IActionResult> CompanyCreateAndUpdate([FromBody] CompanyDTO companyDTO)
        {
            var data = await _companyServiceClient.Insert(companyDTO);
            return Json(data.ToString());
        }


        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

HumanResourceSuite.WebFront/Views/Employee/_Address.cshtml
@{
    ViewData["Title"] = "Self Details";
    Layout = "~/Views/Shared/_LayoutEmployeeMaster.cshtml";

}


<body>

    <main id="main">
        <!-- Bread crumb and right sidebar toggle -->
        <!-- ============================================================== -->
        <div class="page-breadcrumb bg-white">
            <div class="row align-items-center">
                <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
                    <h4 class="page-title">Dashboard</h4>
                </div>
                <div class="col-lg-9 col-sm-8 col-md-8 col-xs-12">
                    <div class="d-md-flex">
                        <ol class="breadcrumb ms-auto">
                            <li><a href="#" class="fw-normal">Bank Details</a></li>
                        </ol>
                        <a href="" target="_blank"
                           class="btn btn-danger  d-none d-md-block pull-right ms-3 hidden-xs hidden-sm waves-effect waves-light text-white">

                        </a>
                    </div>
                </div>
            </div>
            <!-- /.col-lg-12 -->
        </div>
        <!-- ============================================================== -->
        <!-- End Bread crumb and right sidebar toggle -->
        <!-- ============================================================== -->

        <br />


        <!-- ============================================================== -->
        <!-- Container fluid  -->
        <!-- ============================================================== -->
        <div class="container-fluid">

            <div class="row">

                <!-- Column -->
                <div class="col-lg-12 col-xlg-12 col-md-12">
                    <div class="card">
                        <div class="card-body">
                            <form class="form-horizontal form-material">
                                <div class="form-group">
                                    <div class="row">
                                        <div class="col-md-4  border-bottom p-0">
                                            <label class="p-0">Employee Code</label>
                                            <input type="text" class="form-control  p-0 border-0" placeholder="12345" aria-label="First name">
                                        </div>
                                        <div class="col-md-4  border-bottom p-0">
                                            <label class="p-0">Type</label>
                                            <input type="text" class="form-control  p-0 border-0" placeholder="Type" aria-label="Last name">
                                        </div>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <div class="row">
                                        <div class="col-md-12 border-bottom p-0">
                                            <label class="p-0">Address</label>
                                            <input type="text" class="form-control  p-0 border-0" placeholder="Address" aria-label="First name">
                                        </div>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <div class="row">
                                        <div class="col-md-4 border-bottom p-0">
                                            <label class="p-0">Country</label>
                                            <select class="form-select shadow-none p-0 border-0 form-control-line">
                                                <option>India</option>
                                                <option>USA</option>
                                            </select>
                                        </div>
                                        <div class="col-md-4  border-bottom p-0">
                                            <label class="p-0">State</label>
                                            <select class="form-select shadow-none p-0 border-0 form-control-line">
                                                <option>Delhi</option>
                                                <option>Haryana</option>

                                            </select>
                                        </div>
                                        <div class="col-md-4  border-bottom p-0">
                                            <label class="p-0">City</label>
                                            <select class="form-select shadow-none p-0 border-0 form-control-line">
                                                <option>Delhi</option>
                                                <option>Haryana</option>
                                            </select>
                                        </div>
                                    </div>
                                </div>

                                <div class="form-group mb-4">
                                    <div class="col-sm-12">
                                        <button class="btn btn-success">Submit</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
                <!-- Column -->

            </div>

        </div>

    </main>

    @section Scripts
{
        <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.1/moment.min.js"></script>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/js/bootstrap-datetimepicker.min.js"></script>


        <script type="text/javascript">

                                    //$(document).ready(function () {
                                    //    var data = {};



                                    //});

                                    //$(function () {
                                    //    $('#dob').datetimepicker({ defaultDate: new Date() });

                                    //});

        </script>
    }
</body>

HumanResourceSuite.WebFront/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HumarResourceSuite.WebFront</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">HumarResourceSuite.WebFront</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="LeadIndex">Lead</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="CompanyIndex">Company</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="EmployeeIndex">Employee</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Candidate" asp-action="CandidateIndex">Candidate</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - HumarResourceSuite.WebFront - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

HumanResourceSuite.WebFront/Views/Shared/_LayoutMaster.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>@ViewData["Title"] - HRMS Suite</title>
    <meta content="" name="description">

    <meta content="" name="keywords">

    <!-- Favicons -->
    <link href="~/assets/img/favicon.png" rel="icon">
    <link href="~/assets/img/apple-touch-icon.png" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="~/assets/employee/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/assets/employee/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
    <link href="~/assets/employee/aos/aos.css" rel="stylesheet">
    <link href="~/assets/employee/remixicon/remixicon.css" rel="stylesheet">
    <link href="~/assets/employee/swiper/swiper-bundle.min.css" rel="stylesheet">
    <link href="~/assets/employee/glightbox/css/glightbox.min.css" rel="stylesheet">

    <!-- Template Main CSS File -->
    <link href="~/assets/css/style.css" rel="stylesheet">


</head>

<body>

    <header id="header" class="header fixed-top">
        <div class="container-fluid container-xl d-flex align-items-center justify-content-between">

            <a asp-area="" asp-controller="Home" asp-action="Index" class="logo d-flex align-items-center">
                <img src="~/assets/img/logo.png" alt="">
                <span>HRMS</span>
            </a>

            <nav id="navbar" class="navbar">
                <ul>
                    <li><a class="nav-link scrollto active" href="#hero">Home</a></li>
                    <li><a class="nav-link scrollto" href="#about">About</a></li>
                    <li><a class="nav-link scrollto" href="#services">Services</a></li>
                    <li><a class="nav-link scrollto" href="#portfolio">Portfolio</a></li>
                    <li><a class="nav-link scrollto" href="#team">Team</a></li>
                  
                    <li class="dropdown">
                        <a asp-area="" asp-controller="Employee" asp-action="Index"><span>Employee</span> <i class="bi bi-chevron-down"></i></a>
                        <ul>
                            <li><a href="#">Drop Down 1</a></li>
                            <li class="dropdown">
                                <a href="#"><span>Deep Drop Down</span> <i class="bi bi-chevron-right"></i></a>
                                <ul>
                                    <li><a href="#">Deep Drop Down 1</a></li>
                                    <li><a href="#">Deep Drop Down 2</a></li>
                                    <li><a href="#">Deep Drop Down 3</a></li>
                                    <li><a href="#">Deep Drop Down 4</a></li>
                                    <li><a href="#">Deep Drop Down 5</a></li>
                                </ul>
                            </li>
                            <li><a href="#">Drop Down 2</a></li>
                            <li><a href="#">Drop Down 3</a></li>
                            <li><a href="#">Drop Down 4</a></li>
                        </ul>
                    </li>
                    <li><a class="nav-link scrollto" href="#contact">Contact</a></li>
                    <li><a class="getstarted scrollto" asp-controller="Account" asp-action="Login">Get Started</a></li>
                </ul>
                <i class="bi bi-list mobile-nav-toggle"></i>
            </nav><!-- .navbar -->

        </div>
    </header>
    <!-- End Header -->

    <!-- ======= Hero Section ======= -->
    <section id="hero" class="hero d-flex align-items-center">

        <div class="container">
            <div class="row">
                <div class="col-lg-6 d-flex flex-column justify-content-center">
                    <h1 data-aos="fade-up">India’s Best HR Software End-to-End Customized HR Solution</h1>
                    <h2 data-aos="fade-up" data-aos-delay="400">HRMS HCM solution covers HR functions right from hire to retire</h2>
                    <div data-aos="fade-up" data-aos-delay="600">
                        <div class="text-center text-lg-start">
                            <a asp-controller="Account" asp-action="Login" class="btn-get-started scrollto d-inline-flex align-items-center justify-content-center align-self-center">
                                <span>Get Started</span>
                                <i class="bi bi-arrow-right"></i>
                            </a>
                        </div>
                    </div>
                </div>
                <div class="col-lg-6 hero-img" data-aos="zoom-out" data-aos-delay="200">
                    <img src="~/assets/img/hero-img.png" class="img-fluid" alt="">
                </div>
            </div>
        </div>

    </section>
    <!-- End Hero -->


    <main id="main">
        <!-- ======= Main Body Section ======= -->
        <div class="container">
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>


    </main>
    <!-- End #main -->

    <!-- ======= Footer ======= -->
    <footer id="footer" class="footer">

        <div class="footer-newsletter">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-lg-12 text-center">
                        <h4>Our Newsletter</h4>
                        <p>Subscribe us to get the latest news and information</p>
                    </div>
                    <div class="col-lg-6">
                        <form action="" method="post">
                            <input type="email" name="email"><input type="submit" value="Subscribe">
                        </form>
                    </div>
                </div>
            </div>
        </div>

        <div class="footer-top">
            <div class="container">
                <div class="row gy-4">
                    <div class="col-lg-5 col-md-12 footer-info">
                        <a href="index.html" class="logo d-flex align-items-center">
                            <img src="~/assets/img/logo.png" alt="">

                            <span>HRMS</span>
                        </a>
                        <p>"Bring your employees together with HRMS</p>
                        <div class="social-links mt-3">
                            <a href="#" class="twitter"><i class="bi bi-twitter"></i></a>
                            <a href="#" class="facebook"><i class="bi bi-facebook"></i></a>
                            <a href="#" class="instagram"><i class="bi bi-instagram bx bxl-instagram"></i></a>
                            <a href="#" class="linkedin"><i class="bi bi-linkedin bx bxl-linkedin"></i></a>
                        </div>
                    </div>

                    <div class="col-lg-2 col-6 footer-links">
                        <h4>Useful Links</h4>
                        <ul>
                            <li><i class="bi bi-chevron-right"></i> <a href="#">Home</a></li>
                            <li><i class="bi bi-chevron-right"></i> <a href="#">About us</a></li>
                            <li><i class="bi bi-chevron-right"></i> <a href="#">Services</a></li>
                            <li><i class="bi bi-chevron-right"></i> <a href="#">Terms of service</a></li>
                            <li><i class="bi bi-chevron-right"></i> <a href="#">Privacy policy</a></li>
                        </ul>
                    </div>

                    <div class="col-lg-2 col-6 footer-links">
                        <h4>Our Services</h4>
                        <ul>
                            <li><i class="bi bi-chevron-right"></i> <a href="#">Web Design</a></li>
                            <li><i class="bi bi-chevron-right"></i> <a href="#">Web Development</a></li>
                            <li><i class="bi bi-chevron-right"></i> <a href="#">Product Management</a></li>
                            <li><i class="bi bi-chevron-right"></i> <a href="#">Marketing</a></li>
                            <li><i class="bi bi-chevron-right"></i> <a href="#">Graphic Design</a></li>
                        </ul>
                    </div>

                    <div class="col-lg-3 col-md-12 footer-contact text-center text-md-start">
                        <h4>Contact Us</h4>
                        <p>
                            C-76A - 2nd Floor <br>
                            Shalimar Bagh , Delhi 110088<br>
                            India <br><br>
                            <strong>Phone:</strong> +91 96435 90797<br>
                            <strong>Email:</strong> info@rpvdigitalmarketing.com<br>
                        </p>

                    </div>

                </div>
            </div>
        </div>

        <div class="container">
            <div class="copyright">
                &copy; Copyright <strong><span>HRMS</span></strong>. All Rights Reserved
            </div>
            @*<div class="credits">
                 All the links in the footer should remain intact.
                 You can delete the links only if you purchased the pro version.
                 Licensing information: https://bootstrapmade.com/license/
                 Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/flexstart-bootstrap-startup-template/
                Designed by <a href="https://bootstrapmade.com/">VAP Team</a>
                        </div>*@
        </div>
    </footer>
    <!-- End Footer -->

    <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

    <!-- Vendor JS Files -->
    <script src="~/assets/employee/bootstrap/js/bootstrap.bundle.js"></script>
    <script src="~/assets/employee/aos/aos.js"></script>
    <script src="~/assets/employee/php-email-form/validate.js"></script>
    <script src="~/assets/employee/swiper/swiper-bundle.min.js"></script>
    <script src="~/assets/employee/purecounter/purecounter.js"></script>
    <script src="~/assets/employee/isotope-layout/isotope.pkgd.min.js"></script>
    <script src="~/assets/employee/glightbox/js/glightbox.min.js"></script>

    <!-- Template Main JS File -->
    <script src="~/assets/js/main.js"></script>

    @RenderSection("Scripts", required: false)

</body>

</html>